name: Build docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate docs
      run : |
        if [ -d docs ]; then rm -r docs/*; fi
        pdoc --html --output-dir docs src
        mv docs/src/* docs
        rm -d docs/src
    
    - name: Commit changes
      run: |
        git config --local user.email "build-docs@github.com"
        git config --local user.name "Build docs CI"
        git add .
        git commit -m "Docs actualizados"
        git push
